name: Bug report 🐛
description: Use this if you've found a bug
title: "Bug: [Short description of the bug]"
labels:
  - type/bug

body:
  - type: markdown
    attributes:
      value: |
        Before you post, make sure to check for existing bug reports of the issue:
        https://github.com/CasparCG/server/issues?q=+is%3Aissue+label%3Atype%2Fbug

  - type: textarea
    attributes:
      label: Observed Behavior
      description: What happened?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected behaviour
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps to reproduce
      description: How can we reproduce the issue?
      value: |
        1.
        2.
        3. ...
    validations:
      required: true

  - type: textarea
    attributes:
      label: Environment
      description: What version of CasparCG and OS are you using?
      value: |
        * Commit: [e.g. ab1234c]
        * Server version: [e.g. v2.2]
        * Operating system: [e.g. Windows 10]
    validations:
      required: true
      