#! /bin/bash

source $(dirname "$0")/image-versions

GIT_HASH=$(git rev-parse --verify --short HEAD)

docker build -t casparcg/server \
  --build-arg CC \
  --build-arg CXX \
  --build-arg PROC_COUNT \
  --build-arg GIT_HASH \
  --build-arg IMAGE_FFMPEG \
  -f $PWD/tools/linux/Dockerfile $PWD

