#!/bin/bash

source $(dirname "$0")/image-versions

docker pull $IMAGE_FFMPEG docker build -t $IMAGE_FFMPEG --build-arg PROC_COUNT -f tools/linux/ffmpeg/Dockerfile tools/linux

if [ "$CASPARCG_PUSH_IMAGES" = true ]; then
  docker push $IMAGE_FFMPEG
fi
