#!/bin/bash

source $(dirname "$0")/image-versions

docker pull $IMAGE_BASE || docker build -t $IMAGE_BASE tools/linux/base
docker pull $IMAGE_CEF || docker build -t $IMAGE_CEF --build-arg PROC_COUNT --build-arg IMAGE_BASE tools/linux/cef
docker pull $IMAGE_BOOST || docker build -t $IMAGE_BOOST --build-arg PROC_COUNT --build-arg IMAGE_BASE tools/linux/boost
docker pull $IMAGE_FFMPEG || docker build -t $IMAGE_FFMPEG --build-arg PROC_COUNT --build-arg IMAGE_BASE tools/linux/ffmpeg

# TODO - push images if auth variables are defined
