#!/bin/bash

source $(dirname "$0")/image-versions

# CEF
echo "Extracting CEF"
rm -Rf /opt/cef
tempContainer=$(docker create $IMAGE_CEF sh)
docker cp $tempContainer:/opt/cef /opt/cef
docker rm -v $tempContainer

# FFmpeg
echo "Extracting FFmpeg"
rm -Rf /opt/ffmpeg
tempContainer=$(docker create $IMAGE_FFMPEG sh)
docker cp $tempContainer:/opt/ffmpeg /opt/ffmpeg
docker rm -v $tempContainer

# Boost
echo "Extracting Boost"
rm -Rf /opt/boost
tempContainer=$(docker create $IMAGE_BOOST sh)
docker cp $tempContainer:/opt/boost /opt/boost
docker rm -v $tempContainer
