#!/bin/bash

source $(dirname "$0")/image-versions

# FFmpeg
echo "Extracting FFmpeg"
rm -Rf /opt/ffmpeg
tempContainer=$(docker create $IMAGE_FFMPEG sh)
docker cp $tempContainer:/opt/ffmpeg /opt/ffmpeg
docker rm -v $tempContainer
