#!/bin/bash

export IMAGE_PREFIX=ghcr.io/casparcg/server/

export IMAGE_BASE=${IMAGE_PREFIX}base:jammy-0
export IMAGE_BOOST=${IMAGE_PREFIX}boost:1.67-2
export IMAGE_FFMPEG=${IMAGE_PREFIX}ffmpeg:5.1.3-1
