#!/bin/sh

fail() {
    echo "$1" 1>&2
    exit 1
}

export STAGING_DIRECTORY="/build/staging"

rm -rf "$STAGING_DIRECTORY" || fail "Could not delete $STAGING_DIRECTORY"
mkdir "$STAGING_DIRECTORY" || fail "Could not create $STAGING_DIRECTORY"
mkdir "$STAGING_DIRECTORY/bin" || fail "Could not create $STAGING_DIRECTORY/bin"
mkdir "$STAGING_DIRECTORY/lib" || fail "Could not create $STAGING_DIRECTORY/lib"
mkdir "$STAGING_DIRECTORY/template" || fail "Could not create $STAGING_DIRECTORY/template"
mkdir "$STAGING_DIRECTORY/media" || fail "Could not create $STAGING_DIRECTORY/media"

# Copy compiled binary
echo Copying binary...
cp -f  /build/shell/casparcg "$STAGING_DIRECTORY/bin/" || fail "Could not copy server executable"


# Copy dependencies
echo Copying dependencies...
cp -rf /build/shell/lib* "$STAGING_DIRECTORY/lib/" || fail "Could not copy server libraries"
cp -f  /source/shell/LiberationSans-Regular.ttf "$STAGING_DIRECTORY/" || fail "Could not copy LiberationSans-Regular.ttf"
cp -f  /source/shell/casparcg.config "$STAGING_DIRECTORY/" || fail "Could not copy server config"
cp -f  /source/shell/run.sh "$STAGING_DIRECTORY/" || fail "Could not copy run.sh"
cp -Rf /build/shell/locales "$STAGING_DIRECTORY/bin/" || fail "Could not copy server CEF locales"
cp -f  /build/shell/*.pak "$STAGING_DIRECTORY/" || fail "Could not copy CEF resources"

# Copy documentation
echo Copying documentation...
cp -f /source/CHANGELOG "$STAGING_DIRECTORY/" || fail "Could not copy CHANGELOG"
cp -f /source/README "$STAGING_DIRECTORY/" || fail "Could not copy README"
cp -f /source/LICENSE "$STAGING_DIRECTORY/" || fail "Could not copy LICENSE"

# Create tar.gz file
echo Creating tag.gz...
tar -cvzf "/build/products/CasparCG_Server_ubuntu-17.10.tar.gz" "$STAGING_DIRECTORY" || fail "Could not create archive"
